# Generated by Django 4.1.3 on 2022-11-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0033_alter_product_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='body',
            field=models.CharField(db_index=True, max_length=500, null=True, verbose_name='توضیحات اصلی محصول'),
        ),
    ]
