# Generated by Django 4.1.3 on 2022-11-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0034_alter_product_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='body',
            field=models.TextField(db_index=True, max_length=500, null=True, verbose_name='توضیحات اصلی محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.TextField(db_index=True, max_length=150, null=True, verbose_name='توضیحات کوتاه'),
        ),
    ]
