# Generated by Django 4.1.3 on 2022-11-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0035_alter_product_body_alter_product_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgallery',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='نام عکس'),
        ),
    ]
