# Generated by Django 4.1.3 on 2022-11-20 10:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_module', '0017_alter_blog_body_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='body_image',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
