# Generated by Django 4.1.3 on 2022-11-21 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customersquots',
            new_name='CustomersQuotes',
        ),
    ]
