# Generated by Django 4.1.3 on 2022-11-21 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0002_rename_customersquots_customersquotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovingText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, null=True, verbose_name='متن متحرک صفحه اصلی')),
            ],
        ),
    ]
