# Generated by Django 4.1.3 on 2022-11-23 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0003_movingtext'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movingtext',
            options={'verbose_name': 'متن متحرک', 'verbose_name_plural': 'متن های متحرک'},
        ),
    ]
