# Generated by Django 4.1.3 on 2022-11-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', null=True, upload_to='images/about/%Y/%m/%d', verbose_name='تصویر اصلی')),
                ('body', models.TextField(db_index=True, max_length=500, null=True, verbose_name='توضیحات اصلی درباره زیتا')),
            ],
            options={
                'verbose_name': 'درباره ما',
                'verbose_name_plural': 'درباره ما',
            },
        ),
    ]
