# Generated by Django 4.1.3 on 2022-11-23 12:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='body',
            field=ckeditor.fields.RichTextField(default='', verbose_name='متن درباره ما'),
        ),
    ]
